name: Build and install deb packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MDB_LOCALES_DEB_CACHE_KEY: 'mdb-locales-deb'
  MDB_LOCALES_DEB_NAME: 'mdb-locales_0.0.1-1_amd64.deb'
  LIBMDBLOCALES_DEB_NAME: 'libmdblocales1_0.0.1-1_amd64.deb'

jobs:
  build_mdb_locales:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        path: ./src
    - name: Cache resulting deb packages
      id: cache-mdb-locales
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.MDB_LOCALES_DEB_NAME }}
          ${{ env.LIBMDBLOCALES_DEB_NAME }}
        key: ${{ env.MDB_LOCALES_DEB_CACHE_KEY }}
    - name: Install build deps
      run: |
        sudo apt update
        sudo apt install -y debhelper build-essential
    - name: Build deb packages
      working-directory: ./src
      run: dpkg-buildpackage -us -uc
    - uses: actions/upload-artifact@v4
      with:
        name: upload-artifacts
        path: |
          ./mdb-locales*
          ./libmdblocales*

  patch_and_build_postgresql:
    runs-on: ubuntu-22.04
    needs: [ build_mdb_locales ]
    steps:
    - uses: actions/checkout@v4
      with:
        path: ./src
    - uses: actions/checkout@v4
      with:
        repository: postgres/postgres
        path: ./postgres-src
        ref: 'refs/tags/REL_16_0'
    - name: Load mdb-locales packages
      id: cache-mdb-locales
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.MDB_LOCALES_DEB_NAME }}
          ${{ env.LIBMDBLOCALES_DEB_NAME }}
        key: ${{ env.MDB_LOCALES_DEB_CACHE_KEY }}
    - name: Fail if no cached packages
      if: steps.cache-images.outputs.cache-hit != 'true'
      run: |
        echo "Failed to fetch cached docker images. Will now exit..."
        exit 1
    - name: Install generated deb packages
      run: sudo dpkg -i *.deb
    - name: Install PostgreSQL build deps
      run: sudo apt-get install build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev libssl-dev libxml2-utils xsltproc ccache pkg-config
